### ISSUE TITLE
Error on the Raspberry Pi

### ISSUE THREAD

**Issue by echtor** [davidgengenbach/ebay-kleinanzeigen-crawler#1]
Hi, i get this error on Raspbian: 
/var/www/html/ebay# ./crawl.py
Starting to crawl. Options:
Namespace(json_out='data/results.json', options='preis:0:20/', page_end=10, page_start=1, url='https://www.ebay-kleinanzeigen.de/s-64283/preis:0:20//%s/l4896')

        Crawling page: 1/10
Traceback (most recent call last):
  File "./crawl.py", line 63, in <module>
    main()
  File "./crawl.py", line 17, in main
    results += get_results(browser, args.url, page_num)
  File "./crawl.py", line 49, in get_results
    for el in page.soup.select('article.aditem'):
AttributeError: 'Response' object has no attribute 'soup'
greetz

**Comment by davidgengenbach** [comment]
Can you check the URL you have given in the arguments? `https://www.ebay-kleinanzeigen.de/s-64283/preis:0:20//%s/l4896`
It seems to have two slashs `//` in it?

**Comment by cre-mer** [comment]
I'm facing the same problem:
This is my command:
`./crawl.py --url https://www.ebay-kleinanzeigen.de/s-saarbruecken/peugeot/k0l382r50`

This is my output:
```bash
Starting to crawl. Options:
Namespace(json_out='data/results.json', options='preis:0:20/', page_end=10, page_start=1, url='https://www.ebay-kleinanzeigen.de/s-64283/preis:0:20//%s/l4896')

	Crawling page: 1/10
Traceback (most recent call last):
  File "./crawl.py", line 63, in <module>
    main()
  File "./crawl.py", line 17, in main
    results += get_results(browser, args.url, page_num)
  File "./crawl.py", line 45, in get_results
    page = browser.get('https://www.ebay-kleinanzeigen.de/s-saarbruecken/peugeot/k0l382r50' % ('seite:' + str(page)))
TypeError: not all arguments converted during string formatting
```

**Comment by davidgengenbach** [comment]
@cre-mer Please execute `./crawl.py --help` for an explanation of the available options.
In particular, see the description of the `--url` option: you **must** have a `%s` part in your `--url` argument.

Can you please do `git pull` and try again with:
```
$ ./crawl.py --url="https://www.ebay-kleinanzeigen.de/s-saarbruecken/%s/peugeot/k0l382"
Starting to crawl. Options:
Namespace(json_out='data/results.json', options='', page_end=10, page_start=1, url='https://www.ebay-kleinanzeigen.de/s-saarbruecken//%s/peugeot/k0l382')

	Crawling page:  1/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:1/peugeot/k0l382)
	Crawling page:  2/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:2/peugeot/k0l382)
	Crawling page:  3/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:3/peugeot/k0l382)
	Crawling page:  4/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:4/peugeot/k0l382)
	Crawling page:  5/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:5/peugeot/k0l382)
	Crawling page:  6/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:6/peugeot/k0l382)
	Crawling page:  7/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:7/peugeot/k0l382)
	Crawling page:  8/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:8/peugeot/k0l382)
	Crawling page:  9/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:9/peugeot/k0l382)
	Crawling page: 10/10 (https://www.ebay-kleinanzeigen.de/s-saarbruecken//seite:10/peugeot/k0l382)
```


```
$ ./crawl.py --help
usage: crawl.py [-h] [--url URL] [--page-start PAGE_START]
                [--page-end PAGE_END] [--json-out JSON_OUT]
                [--options OPTIONS]

Crawl ebay kleinanzeigen

optional arguments:
  -h, --help            show this help message and exit
  --url URL             The start url. Must have a [percent-sign]s portion in
                        the url to insert the "options" like the page num,
                        price etc. (default: https://www.ebay-
                        kleinanzeigen.de/s-saarbruecken/%s/peugeot/k0l382)
  --page-start PAGE_START
                        The page number to start at (default: 1)
  --page-end PAGE_END   The page number to end at (default: 10)
  --json-out JSON_OUT   The path for the output json. (default:
                        data/results.json)
  --options OPTIONS     Options for kleinanzeigen. Get from the site. Example:
                        "--options preis:0:20" (default: )
```

**Comment by davidgengenbach** [comment]
Closed due to inactivity! Thanks for raising the issue 🥳
